---
apiVersion: v1
kind: Service
metadata:
  namespace: wtm
  name: service-int-postgres-wtm
spec:
  ports:
      #port: is the abstracted Service port, which can be any port other pods use to access the Service
    - port: 5432
      #targetPort: is the port the container accepts traffic on
      targetPort: 5432
      protocol: TCP
      name: internal
  selector:
    app.kubernetes.io/name: postgresql-wtm
---
apiVersion: v1
kind: Service
metadata:
  name: service-lb-wtm
  namespace: wtm
spec:
  selector:
    app.kubernetes.io/name: wtm
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000