---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wtm-01
  namespace: wtm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: vultr-block-storage-retain